export const TOGGLE_UNIT = 'TOGGLE_UNIT';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_TAB = 'SET_TAB';
export const SET_WEATHER_DATA_SUCCESS = 'SET_WEATHER_DATA_SUCCESS';
export const SET_WEATHER_DATA_FAILED = 'SET_WEATHER_DATA_FAILED';
export const LOADING_OFF = 'LOADING_OFF';
export const LOADING_ON = 'LOADING_ON';
